server: 
  log_level: info

logs:
  configs:
    - name: docker-logs
      positions:
        filename: /tmp/positions.yml
      scrape_configs:
        - job_name: docker-logs
          docker_sd_configs:
            - host: unix:///var/run/docker.sock
          relabel_configs:
            - source_labels: ['__meta_docker_container_name']
              target_label: 'container'
              replacement: '${1}'
            - source_labels: ['__meta_docker_container_log_stream']
              target_label: 'stream'
            - source_labels: ['__meta_docker_container_image']
              target_label: 'image'
      clients:
        - url: http://loki:3100/loki/api/v1/push